# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f06c7d1c781c767cd8839b87100a8ff72faa0c1ce28684299b2376d69467e6938da2ce166c70a99f9a9ec1fa6ab8c23cb96dacb08f443d95b030797948aec7f2

test:
  secret_key_base: f986a802920ac3d00a9b4aef6ea91a561d479dc5bcdb9c7f040de0a56aa10854e56f0efb233d1ec2644ef9709efafe698997e6c7e517e2c9ad3feb83c93e0486

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
